# Generated by Django 4.2.7 on 2023-11-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConciergeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmodel',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='restaurantmodel',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantmodel',
            name='review',
            field=models.FloatField(default=0.0),
        ),
    ]
