# Generated by Django 4.2.6 on 2023-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConciergeApp', '0002_remove_restaurantmodel_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurants/'),
        ),
    ]
