# Generated by Django 4.2.7 on 2023-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConciergeApp', '0003_alter_restaurantmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
