# Generated by Django 4.2.6 on 2023-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConciergeApp', '0004_restaurantmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='numberOfReviews',
            field=models.IntegerField(default=0),
        ),
    ]
