# Generated by Django 4.2.7 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConciergeApp', '0006_usermodel_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
